import { CONFIG } from './config'

export const JOKES = [
  {solution: 'WHITE', question:'⚰️🎥1️⃣', pre:'', post:'', fact:'On January 1, many learned of Golden Girls star Betty White\'s death the prior day, just 18 days before she would have turned 100.'},
  {solution: 'WHITE', question:'⚰️🎥1️⃣', pre:'', post:'', fact:'On January 1, many learned of Golden Girls star Betty White\'s death the prior day, just 18 days before she would have turned 100.'},
  {solution: 'BETTY', question:'⚰️🎥1️⃣', pre:'', post:'', fact:'On January 1, many learned of Golden Girls star Betty White\'s death the prior day, just 18 days before she would have turned 100.'},
  {solution: 'BETTY', question:'⚰️🎥1️⃣', pre:'', post:'', fact:'On January 1, many learned of Golden Girls star Betty White\'s death the prior day, just 18 days before she would have turned 100.'},
  {solution: 'SAGET', question:'⚰️😂1️⃣', pre:'', post:'', fact:'On January 9,  American stand-up comedian, actor, and television host Bob Saget died.'},
  {solution: 'SAGET', question:'⚰️😂1️⃣', pre:'', post:'', fact:'On January 9,  American stand-up comedian, actor, and television host Bob Saget died.'},
  {solution: 'ENEMY', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 1, Imagine Dragon\'s Enemy (theme song from the show Arcane) was released for radio in the United States.'},
  {solution: 'ENEMY', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 1, Imagine Dragon\'s Enemy (theme song from the show Arcane) was released for radio in the United States.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'BRUNO', question:'🎶🤫2️⃣', pre:'', post:'', fact:'On February 12, "We Don\'t Talk About Bruno" reached number one on the Billboard Global 200 chart.'},
  {solution: 'CHINA', question:'🥇2️⃣', pre:'', post:'', fact:'In February, Beijing hosted the Winter Olympics.'},
  {solution: 'CHINA', question:'🥇2️⃣', pre:'', post:'', fact:'In February, Beijing hosted the Winter Olympics.'},
  {solution: 'CHINA', question:'🥇2️⃣', pre:'', post:'', fact:'In February, Beijing hosted the Winter Olympics.'},
  {solution: 'ELDEN', question:'🎮⭕2️⃣', pre:'', post:'', fact:'On February 25, the videogame Elden Ring was released.'},
  {solution: 'ELDEN', question:'🎮⭕2️⃣', pre:'', post:'', fact:'On February 25, the videogame Elden Ring was released.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'SOLAR', question:'⚡3️⃣', pre:'', post:'', fact:'Approximately in March, humans achieved a combined terawatt output of solar capacity.'},
  {solution: 'TWEET', question:'📈🐦4️⃣', pre:'', post:'', fact:'On April 14, Elon Musk announced his intention to purchase Twitter, which concluded on October 27.'},
  {solution: 'TWEET', question:'📈🐦4️⃣', pre:'', post:'', fact:'On April 14, Elon Musk announced his intention to purchase Twitter, which concluded on October 27.'},
  {solution: 'HOLES', question:'🛰️5️⃣', pre:'', post:'', fact:'On May 12, astronomers revealed the first image of the black hole at the center of our galaxy, and the second image ever taken of a black hole.'},
  {solution: 'HOLES', question:'🛰️5️⃣', pre:'', post:'', fact:'On May 12, astronomers revealed the first image of the black hole at the center of our galaxy, and the second image ever taken of a black hole.'},
  {solution: 'BLACK', question:'🛰️5️⃣', pre:'', post:'', fact:'On May 12, astronomers revealed the first image of the black hole at the center of our galaxy, and the second image ever taken of a black hole.'},
  {solution: 'BLACK', question:'🛰️5️⃣', pre:'', post:'', fact:'On May 12, astronomers revealed the first image of the black hole at the center of our galaxy, and the second image ever taken of a black hole.'},
  {solution: 'COVID', question:'😷5️⃣', pre:'', post:'', fact:'On May 17 the US surpassed 1 million COVID-19 deaths.'},
  {solution: 'COVID', question:'😷5️⃣', pre:'', post:'', fact:'On May 17 the US surpassed 1 million COVID-19 deaths.'},
  {solution: 'LEAKS', question:'🏛️🤰🏻5️⃣', pre:'', post:'', fact:'On May 2, Politico released a leaked draft opinion in Dobbs v. Jackson Women\'s Health Organization, which had five votes to overturn Roe v. Wade.'},
  {solution: 'LEAKS', question:'🏛️🤰🏻5️⃣', pre:'', post:'', fact:'On May 2, Politico released a leaked draft opinion in Dobbs v. Jackson Women\'s Health Organization, which had five votes to overturn Roe v. Wade.'},
  {solution: 'TEXAS', question:'🏫😢5️⃣', pre:'', post:'', fact:'On May 24, 19 children and 2 adults were killed in a shooting at Robb Elementary School in Uvalde County.'},
  {solution: 'TEXAS', question:'🏫😢5️⃣', pre:'', post:'', fact:'On May 24, 19 children and 2 adults were killed in a shooting at Robb Elementary School in Uvalde County.'},
  {solution: 'VECNA', question:'🚲👾5️⃣', pre:'', post:'', fact:'On May 27, Stranger Things Season 4 was released, which featured the monster Vecna.'},
  {solution: 'VECNA', question:'🚲👾5️⃣', pre:'', post:'', fact:'On May 27, Stranger Things Season 4 was released, which featured the monster Vecna.'},
  {solution: 'EDDIE', question:'🚲👾5️⃣', pre:'', post:'', fact:'On May 27, Stranger Things Season 4 was released, which featured the new character Eddie Munson.'},
  {solution: 'EDDIE', question:'🚲👾5️⃣', pre:'', post:'', fact:'On May 27, Stranger Things Season 4 was released, which featured the new character Eddie Munson.'},
  {solution: 'CREEL', question:'🚲👾5️⃣', pre:'', post:'', fact:'On May 27, Stranger Things Season 4 was released, which included the mysterious character Victor Creel.'},
  {solution: 'CREEL', question:'🚲👾5️⃣', pre:'', post:'', fact:'On May 27, Stranger Things Season 4 was released, which included the mysterious character Victor Creel.'},
  {solution: 'AMBER', question:'⚖️6️⃣', pre:'', post:'', fact:'On June 1, the verdict was announced in the highly publicized John C. Depp, II v. Amber Laura Heard case.'},
  {solution: 'AMBER', question:'⚖️6️⃣', pre:'', post:'', fact:'On June 1, the verdict was announced in the highly publicized John C. Depp, II v. Amber Laura Heard case.'},
  {solution: 'HEARD', question:'⚖️6️⃣', pre:'', post:'', fact:'On June 1, the verdict was announced in the highly publicized John C. Depp, II v. Amber Laura Heard case.'},
  {solution: 'HEARD', question:'⚖️6️⃣', pre:'', post:'', fact:'On June 1, the verdict was announced in the highly publicized John C. Depp, II v. Amber Laura Heard case.'},
  {solution: 'BROWN', question:'🏛️👩🏾‍⚖️6️⃣', pre:'', post:'', fact:'On June 30, Justice Ketanji Brown Jackson was sworn in as a Supreme Court Justice.'},
  {solution: 'BROWN', question:'🏛️👩🏾‍⚖️6️⃣', pre:'', post:'', fact:'On June 30, Justice Ketanji Brown Jackson was sworn in as a Supreme Court Justice.'},
  {solution: 'COURT', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'COURT', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'DOBBS', question:'🏛️🤰🏻6️⃣', pre:'', post:'', fact:'On June 24, the U.S. Supreme Court released its decision in Dobbs v. Jackson Women\'s Health Organization, overturning the constitutional right to abortion.'},
  {solution: 'JAMES', question:'🛰️7️⃣', pre:'', post:'', fact:'On July 12, the first five scientific images taken by the James Webb Space Telescope were released to the public.'},
  {solution: 'JAMES', question:'🛰️7️⃣', pre:'', post:'', fact:'On July 12, the first five scientific images taken by the James Webb Space Telescope were released to the public.'},
  {solution: 'SPACE', question:'🛰️7️⃣', pre:'', post:'', fact:'On July 12, the first five scientific images taken by the James Webb Space Telescope were released to the public.'},
  {solution: 'SPACE', question:'🛰️7️⃣', pre:'', post:'', fact:'On July 12, the first five scientific images taken by the James Webb Space Telescope were released to the public.'},
  {solution: 'NOVAK', question:'🎾8️⃣', pre:'', post:'', fact:'In August, tennis champion Novak Djokovic was unable to participate in the US Open due to refusal to get the COVID-19 vaccine.'},
  {solution: 'NOVAK', question:'🎾8️⃣', pre:'', post:'', fact:'In August, tennis champion Novak Djokovic was unable to participate in the US Open due to refusal to get the COVID-19 vaccine.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'NANCY', question:'🇹🇼8️⃣', pre:'', post:'', fact:'On August 2, Nancy Pelosi visited Taiwan, the highest-ranking US official to do so in 25 years.'},
  {solution: 'HOUSE', question:'🐉🎥8️⃣', pre:'', post:'', fact:'On August 21, Game of Thrones spin-off "House of the Dragon" was released.'},
  {solution: 'HOUSE', question:'🐉🎥8️⃣', pre:'', post:'', fact:'On August 21, Game of Thrones spin-off "House of the Dragon" was released.'},
  {solution: 'LOANS', question:'🏫💰8️⃣', pre:'', post:'', fact:'On August 24, the White House announced plans to cancel $10,000 of student debt for low- to middle-income borrowers.'},
  {solution: 'LOANS', question:'🏫💰8️⃣', pre:'', post:'', fact:'On August 24, the White House announced plans to cancel $10,000 of student debt for low- to middle-income borrowers.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'TARIQ', question:'🌽👦🏿8️⃣', pre:'', post:'', fact:'On August 28, a video featuring Tariq, the "Corn Kid", and "CEO of Corn" went viral on social media.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'DALLE', question:'🎨🤖9️⃣', pre:'', post:'', fact:'On September 28, OpenAI made access to their image-creation tool DALL-E open to the public without a waitlist.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'QUEEN', question:'⚰️🇬🇧9️⃣', pre:'', post:'', fact:'On September 8, Queen Elizabeth II died.'},
  {solution: 'ARIEL', question:'🧜🏿‍♀️9️⃣', pre:'', post:'', fact:'On September 9, Disney revealed the trailer for the upcoming live-action Little Mermaid, featuring Halle Bailey as Ariel.'},
  {solution: 'ARIEL', question:'🧜🏿‍♀️9️⃣', pre:'', post:'', fact:'On September 9, Disney revealed the trailer for the upcoming live-action Little Mermaid, featuring Halle Bailey as Ariel.'},
  {solution: 'BLACK', question:'🧜🏿‍♀️9️⃣', pre:'', post:'', fact:'On September 9, Disney revealed the trailer for the upcoming live-action Little Mermaid, featuring Halle Bailey as Ariel.'},
  {solution: 'BLACK', question:'🧜🏿‍♀️9️⃣', pre:'', post:'', fact:'On September 9, Disney revealed the trailer for the upcoming live-action Little Mermaid, featuring Halle Bailey as Ariel.'},
  {solution: 'HIJAB', question:'🇮🇷9️⃣', pre:'', post:'', fact:'In September, many Iranians protested against the hijab after the death of Mahsa Amini.'},
  {solution: 'HIJAB', question:'🇮🇷9️⃣', pre:'', post:'', fact:'In September, many Iranians protested against the hijab after the death of Mahsa Amini.'},
  {solution: 'MAHSA', question:'🇮🇷9️⃣', pre:'', post:'', fact:'In September, many Iranians protested against the hijab after the death of Mahsa Amini.'},
  {solution: 'AMINI', question:'🇮🇷9️⃣', pre:'', post:'', fact:'In September, many Iranians protested against the hijab after the death of Mahsa Amini.'},
  {solution: 'JONES', question:'🤥🔟', pre:'', post:'', fact:'On October 12, a Jury decided conspiracy theorist Alex Jones should pay nearly $1 billion in damages to Sandy Hook families for lies about the school shooting.'},
  {solution: 'JONES', question:'🤥🔟', pre:'', post:'', fact:'On October 12, a Jury decided conspiracy theorist Alex Jones should pay nearly $1 billion in damages to Sandy Hook families for lies about the school shooting.'},
  {solution: 'ORION', question:'🌚1️⃣1️⃣', pre:'', post:'', fact:'In late November, the spacecraft Orion from the Artemis I mission made a close flyby of the far side of the Moon, passing about 130km above the surface.'},
  {solution: 'ORION', question:'🌚1️⃣1️⃣', pre:'', post:'', fact:'In late November, the spacecraft Orion from the Artemis I mission made a close flyby of the far side of the Moon, passing about 130km above the surface.'},
  {solution: 'FRIED', question:'📉1️⃣1️⃣', pre:'', post:'', fact:'On November 11, Sam Bankman-Fried resigned from FTX, and FTX filed for bankruptcy.'},
  {solution: 'FRIED', question:'📉1️⃣1️⃣', pre:'', post:'', fact:'On November 11, Sam Bankman-Fried resigned from FTX, and FTX filed for bankruptcy.'},
  {solution: 'LGBTQ', question:'🏛️1️⃣1️⃣', pre:'', post:'', fact:'On November 29, the Senate, by a vote of 61–39, passed an amended version of the Respect for Marriage Act to require all US states to recognize same-sex marriages.'},
  {solution: 'LGBTQ', question:'🏛️1️⃣1️⃣', pre:'', post:'', fact:'On November 29, the Senate, by a vote of 61–39, passed an amended version of the Respect for Marriage Act to require all US states to recognize same-sex marriages.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'QATAR', question:'⚽️1️⃣2️⃣', pre:'', post:'', fact:'In December, the World Cup was hosted in Qatar.'},
  {solution: 'SMITH', question:'✋🏿🎥3️⃣', pre:'', post:'', fact:'On March 27, Will Smith slapped Chris Rock after the comedian made a joke about Jada Smith\'s alopecia.'},
  {solution: 'SMITH', question:'✋🏿🎥3️⃣', pre:'', post:'', fact:'On March 27, Will Smith slapped Chris Rock after the comedian made a joke about Jada Smith\'s alopecia.'},
  {solution: 'CHRIS', question:'✋🏿🎥3️⃣', pre:'', post:'', fact:'On March 27, Will Smith slapped Chris Rock after the comedian made a joke about Jada Smith\'s alopecia.'},
  {solution: 'CHRIS', question:'✋🏿🎥3️⃣', pre:'', post:'', fact:'On March 27, Will Smith slapped Chris Rock after the comedian made a joke about Jada Smith\'s alopecia.'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'PUTIN', question:'🇷🇺2️⃣', pre:'', post:'', fact:'On 24 February, Putin announced a "special military operation" in the country and "effectively declared war on Ukraine."'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'},
  {solution: 'NUKES', question:'🇷🇺🔟', pre:'', post:'', fact:'On October 27, Vladimir Putin denied having any intentions of using nuclear weapons in Ukraine.'}
]

export const WORDS = JOKES.map(joke => joke.solution).flat()

if (CONFIG.normalization) {
  WORDS.forEach((val, i) => (WORDS[i] = val.normalize(CONFIG.normalization)))
}

function shuffle(array: any[]) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[array[i], array[j]] = [array[j], array[i]]
  }
}

if (CONFIG.shuffle) {
  shuffle(WORDS)
}


if (CONFIG.shuffle) {
  shuffle(JOKES)
}
